name: Build and Push Frontend Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/taskapp-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/taskapp-frontend:${{ github.sha }}

#      - name: Update Helm chart image tag
#        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#        run: |
#          git clone https://x-access-token:${{ secrets.HELMCHARTS_TOKEN }}@github.com/entr0pian/helmcharts.git
#          cd helmcharts
#          sed -i "s/tag: .*/tag: \"${{ github.sha }}\"/" frontend/values.yaml
#          git config user.email "github-actions@github.com"
#          git config user.name "GitHub Actions"
#          git add frontend/values.yaml
#          git commit -m "ci: update frontend image tag to ${{ github.sha }}"
#          git push
